### ISSUE TITLE
Setting field of type boolean to true/false raises type error

### ISSUE THREAD

**Issue by joaobzrr** [dhmk083/dhmk-zustand-lens#17]
This

```ts
export const test = create<{ loading: boolean }>(withLenses({ loading: true }))
```
    
 raises the following error:
 
 ```
Argument of type 'StateCreator<{ loading: true; }, [], []>' is not assignable to parameter of type 'StateCreator<{ loading: boolean; }, [], []>'.
     Types of parameters 'getState' and 'getState' are incompatible.
       Call signature return types '{ loading: boolean; }' and '{ loading: true; }' are incompatible.
         The types of 'loading' are incompatible between these types.
           Type 'boolean' is not assignable to type 'true'.
```

**Comment by dhmk083** [comment]
This is an interesting one. I think it's a Typescript issue or maybe not an issue at all, but rather some Typescript's peculiar behavior.

Because I can reproduce this error with Zustand's built-in middleware too. Here's [a playground link for you.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzXAvnAMyghDgCIAvAVwGcYMA7AEzIG4AoUSWROAd2AwAFgBk0DGmhp5CxUgHIAAkyEgA1gHpqdRkwC0AG3E15ncNHhImaAG4wIEA9PxEScedvrMNIYEyZGfBjoppwM2FAEGMg4AMr02LzscHAGEBhMwAwA5gBccABGDkaM7Ljs7MgQEvDYdACMcAC8KOhYaAA88e0AfAAUAJR9yfyCosZSfUhpGVl5cDBQVDi4A+wDHJXVdAtSMABMza2Y2F0JaP1DIwLCYhKTg809cFOp6Zk5+YvLeANra1sars6ABmI6oE6dbrYS7DFI3cb3Gh9PqSGADJ4vabvOZfJYrP7rCpVIF1GAAFnBbVO0IugzhcGsdmKyMeTWerxmH3m3wJ-2J21qewArFTIWdevSRkz7I5WWiMeysW9Zp8FvjfvygA)

So, you need to use the following pattern instead:

```ts
export const test = create<{ loading: boolean }>()(withLenses((set) => ({ loading: true })))
```

You need to use function overload and explicitly add `set` parameter, even if it will be unused. Also note that with Typescript you should use [curried `create` function](https://github.com/pmndrs/zustand/blob/main/docs/guides/typescript.md#basic-usage).

**Comment by dhmk083** [comment]
Looks like I accidentally resolved this issue 😄
