### ISSUE TITLE
[Question] How do I initialize the store with props?

### ISSUE THREAD

**Issue by bd-charu** [dhmk083/dhmk-zustand-lens#18]
In this example, `initProps` contains data/state only, no actions. It is also not a `lens` object (this is where my problem happens I think). 

I think what I need to do is initialize the props as a `lens` object and merge it with the default state but I don't know how to do that. Any help would be appreciated

```
const useStore = create(withLenses(() => ({
  ...initProps,

  bears: lens(set => ({
    // ...bears state & actions
  })),

  fish: lens(set => ({
    // ...fish state & actions
  })),

  // Placing the initial props here will set the actions to undefined
  // ...initProps
})))
```

**Comment by dhmk083** [comment]
You can't perform any merging inside `withLenses` function, because at this point `lens` objects are not resolved yet (they are just special functions). So the simpliest option would be setting the state just after the store has been created. For this you need to perform a deep merge operation, not a shallow one. 

```ts
import { create } from 'zustand'
import { withLenses, lens, mergeDeep } from '@dhmk/zustand-lens'

const useStore = create(withLenses(() => ({
  bears: lens(set => ({
    // ...bears state & actions
  })),

  fish: lens(set => ({
    // ...fish state & actions
  })),
})))

// merge and set state
useStore.setState(mergeDeep(useStore.getState(), initProps));
```

However, the idiomatic way of doing it would be using zustand's `persist` middleware.

```ts
import { create } from "zustand";
import { persist } from "zustand/middleware";
import { withLenses, lens, mergeDeepLeft } from "@dhmk/zustand-lens";

const useStore = create(
  persist(
    withLenses(() => ({
      bears: lens((set) => ({
        // ...bears state & actions
      })),

      fish: lens((set) => ({
        // ...fish state & actions
      })),
    })),
    // persist options
    {
      name: "my-store", // required, but doesn't matter in our case
      merge: mergeDeepLeft, // need to merge from left to right
      storage: {
        // here you can set initial state by returning an object `{ state: <your_state> }`
        getItem() {
          return { state: initProps }
        },
        // required, but doesn't matter in our case (unless you want to persist your state)
        setItem() {},
        removeItem() {}
      }
    }
  )
);

```

If your inital props are coming from local storage, then you don't even need to write a custom storage. [This page](https://docs.pmnd.rs/zustand/integrations/persisting-store-data) contains more info and examples.

**Comment by bd-charu** [comment]
Thank you so much
