### ISSUE TITLE
Loading a stored state from the Redux Devtools corrupts the actions of the lenses

### ISSUE THREAD

**Issue by pf-costa** [dhmk083/dhmk-zustand-lens#26]
Loving so far this extension to Zustand, thanks for the contribution! 🙏  I'm having however an issue with the devtools middleware.

I have created a very basic store that uses the devtools middleware. 
https://stackblitz.com/edit/vitejs-vite-676yfd?file=src%2FApp.tsx

```typescript
import { create } from 'zustand';
import { devtools, persist, subscribeWithSelector } from 'zustand/middleware';
import { withLenses, lens } from '@dhmk/zustand-lens';

const bears = lens((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}));

const useStore = create(
  devtools(
    withLenses({
      bears: bears,
    }),
    {
      name: 'bears',
      anonymousActionType: 'bears',
    }
  )
);
```

Using the Redux Devtools Chrome extension, if I load a saved state from a previous session, the state variables are indeed reinitialized, however all of the action handlers are `undefined`.  I'm I missing something?

**Comment by dhmk083** [comment]
This is similar to persist middleware issue (#5). When a saved state is loaded, zustand performs a shallow merge with current state. This means that any nested state gets overwritten. 

For persist middleware there is an option to control merge behavior, but for devtools middleware there isn't. It's quite easy to add it, though. Here is a fix ([replace this function](https://github.com/pmndrs/zustand/blob/main/src/middleware/devtools.ts#L203)):

```ts
  const setStateFromDevtools = (st) => {
    const originalIsRecording = isRecording;
    isRecording = false;
    set(s => devtoolsOptions.merge(st, s));
    isRecording = originalIsRecording;
  };
```

If this will be fixed in zustand repo, then you can use deep merge function to make things work:

```ts
import { create } from 'zustand';
import { devtools, persist, subscribeWithSelector } from 'zustand/middleware';
import { withLenses, lens, mergeDeepLeft } from '@dhmk/zustand-lens';

const bears = lens((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}));

const useStore = create(
  devtools(
    withLenses({
      bears: bears,
    }),
    {
      name: 'bears',
      anonymousActionType: 'bears',
      merge: mergeDeepLeft
    }
  )
);
```

**Comment by pf-costa** [comment]
Thanks @dhmk083 will take a look! 🙏
