### ISSUE TITLE
Using lensed slices for scoped stores

### ISSUE THREAD

**Issue by sglmk** [dhmk083/dhmk-zustand-lens#27]
I recently encountered an issue where I needed be able to have dynamic slices as a part of a larger store, and failed to do so using the slices example in the zustand docs. However when I found this repo and it seems to solve my issues, but I am left with a couple questions: 

The structure of the code goes something like so (from bottom to top):

The lens slice:

```
export interface PurchaseHistorySlice {
    items: string[];
    setItems: (newItems: string[]) => void;
}

export const createPurchaseHistorySlice = lens<PurchaseHistorySlice>((set) => ({
    items: [],
    setItems: (newItems) =>
        set(() => {
            return { items: newItems };
        }),
}));

```

And the store containing the slice:
```
export type SingleUserStore = { purchaseHistory: PurchaseHistorySlice };

export const useUserStore = create<SingleUserStore>()(
    devtools(
        withLenses(() => ({
            purchaseHistory: createPurchaseHistorySlice,
        }))
    )
);
```

I don't have much experience with zustand, however I was surprised that the data access to the properties of the `purchaseHistory` slice was not in the 'classic' zustand way:
```
const pruchaseHistory = useUserStore(state => state.purchaseHistory);
const purchaseHistoryData = purchaseHistory(state => state.data);
```

but rather:
`const purchaseHistoryData = purchaseHistory.data;`

How does this affect the renders of the component? Is it equivalent to directly getting a state from the store, or will this be affected by other states changing in the slice?

**Comment by dhmk083** [comment]
This library doesn't provide any hooks or selectors, so in your example you should use shallow equality techniques (such as [this](https://github.com/pmndrs/zustand?tab=readme-ov-file#selecting-multiple-state-slices) or [this](https://github.com/pmndrs/zustand/blob/main/docs/migrations/migrating-to-v5.md#using-custom-equality-functions-such-as-shallow)) to avoid unnecessary re-renders. Otherwise, component will update when `purchaseHistory` slice is changed.

Or you can grab data directly:

```ts
const purchaseHistoryData = useUserStore(state => state.purchaseHistory.data)
```

**Comment by sglmk** [comment]
Thanks!
