### ISSUE TITLE
Doesnt seem to work with persist middleware

### ISSUE THREAD

**Issue by lordvcs** [dhmk083/dhmk-zustand-lens#5]
Everything works fine when not using the persist middleware, however when the persist middleware is used the action function within the nested sub store becomes undefined and doesnt work anymore after page refresh

I have created a sandbox(with nextjs) that recreates the issue that I am talking about https://codesandbox.io/s/zustand-lens-persist-k0pxs5?file=/pages/index.tsx 

Steps to reproduce the issue
1. Open sandbox and on the first load, everything works as intended. clicking on the "change text" button simply appends "s" to the "text"
2. Now refresh the codesandbox browser and you will notice that clicking on the button doesnt do anything(on my local I get the error "TypeError: changeText is not a function")

Any help is appreciated,
Thanks in advance

**Comment by dhmk083** [comment]
You should use a custom [merge function](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#merge) for persist middleware.
Otherwise any nested state (not only lenses) will be overwritten by persisted state.
You can use deep merge function from lodash or any other deep merge function.
Here is your fixed example: [https://codesandbox.io/s/zustand-lens-persist-forked-c8uoe4?file=/store.ts](https://codesandbox.io/s/zustand-lens-persist-forked-c8uoe4?file=/store.ts)

**Comment by roddc** [comment]
> You should use a custom [merge function](https://github.com/pmndrs/zustand/wiki/Persisting-the-store's-data#merge) for persist middleware. Otherwise any nested state (not only lenses) will be overwritten by persisted state. You can use deep merge function from lodash or any other deep merge function. Here is your fixed example: https://codesandbox.io/s/zustand-lens-persist-forked-c8uoe4?file=/store.ts

Hi, this doesn't seem to work, the nested data will be set to default again after the page refresh
